name: ci/cd

on:
  workflow_dispatch:
  push:
    branches: [ main, 'release/**', 'task/**', 'feature/**', 'epic/**']
    tags: ['**']
  pull_request:
    branches: [ main, 'release/**', 'task/**', 'feature/**', 'epic/**']
  # Build once a month, just to be sure things are still working
  schedule:
  - cron: "20 4 19 * *"

jobs:

  core-builds:
    name: Erlang ${{ matrix.otp_version }} build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        otp_version: ['24.3', '25.3']

    steps:
    - uses: actions/checkout@v2
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp_version }}
        rebar3-version: '3.22'
    - name: Check rebar3 Version
      run: rebar3 --version
    - name: Compile
      run: rebar3 compile
    - name: Xref Checks
      run: rebar3 xref
    # - name: Dialyzer
    #   run: rebar3 dialyzer
    - name: Compile Tests
      run: rebar3 as test compile
    - name: Run Unit Tests
      run: rebar3 as test eunit

  module-builds:
    name: Erlang ${{ matrix.otp_version }} lanes '${{ matrix.lanes-module }}' plugin build
    runs-on: ubuntu-latest
    needs: [core-builds]
    defaults:
      run:
        working-directory: ./modules/lanes-${{ matrix.lanes-module }}

    strategy:
      matrix:
        otp_version: ['24.3', '25.3']
        lanes-module: ['elli', 'barista']

    steps:
    - uses: actions/checkout@v2
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp_version }}
        rebar3-version: '3.22'
    - name: Check rebar3 Version
      run: rebar3 --version
    - name: Compile
      run: rebar3 compile
    - name: Xref Checks
      run: rebar3 xref
    - name: Compile Tests
      run: rebar3 as test compile
    - name: Run Unit Tests
      run: rebar3 as test eunit

  lanes-examples-tests:
    name: Erlang ${{ matrix.otp_version }} lanes '${{ matrix.lanes-module }}' example tests run
    runs-on: ubuntu-latest
    needs: [module-builds]
    defaults:
      run:
        working-directory: ./examples/lanes-${{ matrix.lanes-module }}-example

    strategy:
      matrix:
        otp_version: ['24.3', '25.3']
        lanes-module: ['elli', 'barista']

    steps:
    - uses: actions/checkout@v2
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp_version }}
        rebar3-version: '3.22'
    - name: Check rebar3 Version
      run: rebar3 --version
    - name: Compile
      run: rebar3 compile
    - name: Compile Tests
      run: rebar3 as test compile
    - name: Run Unit Tests
      run: rebar3 as test eunit

  old-builds:
    name: Old Erlang ${{ matrix.otp_version }} build
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        otp_version: ['20.3', '21.3', '22.3', '23.3']

    steps:
    - uses: actions/checkout@v2
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp_version }}
        rebar3-version: '3.15'
    - name: Check rebar3 Version
      run: rebar3 --version
    - name: Compile
      run: rebar3 compile
    - name: Xref Checks
      run: rebar3 xref
    # - name: Dialyzer
    #   run: rebar3 dialyzer
    - name: Compile Tests
      run: rebar3 as test compile
    - name: Run Unit Tests
      run: rebar3 as test eunit
